//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desarrollo_Basado_en_Plataformas.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService2")]
    public interface IService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/RegistroDatos", ReplyAction="http://tempuri.org/IService2/RegistroDatosResponse")]
        void RegistroDatos(string nombres, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimientos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService2/RegistroDatos", ReplyAction="http://tempuri.org/IService2/RegistroDatosResponse")]
        System.Threading.Tasks.Task RegistroDatosAsync(string nombres, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimientos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService2Channel : Desarrollo_Basado_en_Plataformas.ServiceReference2.IService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service2Client : System.ServiceModel.ClientBase<Desarrollo_Basado_en_Plataformas.ServiceReference2.IService2>, Desarrollo_Basado_en_Plataformas.ServiceReference2.IService2 {
        
        public Service2Client() {
        }
        
        public Service2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistroDatos(string nombres, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimientos) {
            base.Channel.RegistroDatos(nombres, apellidos, sexo, email, direccion, ciudad, requerimientos);
        }
        
        public System.Threading.Tasks.Task RegistroDatosAsync(string nombres, string apellidos, string sexo, string email, string direccion, string ciudad, string requerimientos) {
            return base.Channel.RegistroDatosAsync(nombres, apellidos, sexo, email, direccion, ciudad, requerimientos);
        }
    }
}
